### PR TITLE
add coverage step and improve tests

### PR DESCRIPTION
**Pull request by gruebel**
- also updated `winnow` to version `0.6+`

### CODE REVIEW

**Review by nimrodkor — COMMENTED** [review]
What's coveralls?

**Comment by gruebel** [comment]
similar to codecov, but I think you need to sign up to it, because I have no permission to do so https://coveralls.io/

**Comment by nimrodkor** [comment]
Signed up for it, and it is enabled for this repo. Does it work now?

**Comment by gruebel** [comment]
ok, I merge this one and see, if a new PR is triggering something.

**Pull request merged**
